<a href="https://colab.research.google.com/github/prasanth5reddy/D2L/blob/master/The%20Basics/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing Libraries

In [1]:
!pip install mxnet

Importing Libraries

In [0]:
import mxnet as mx
from mxnet import nd
import numpy as np

Getting Started

In [3]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
x = x.reshape((3, 4))
x.reshape?
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [5]:
print(x.shape, x.size)

(3, 4) 12


In [6]:
x = nd.arange(14).reshape((3, -1))
print(x.shape, x.size)
x

(3, 4) 12



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
print(nd.zeros((2, 3, 4)), nd.ones((1, 2, 1)))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)> 
[[[1.]
  [1.]]]
<NDArray 1x2x1 @cpu(0)>


In [8]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

Operations

In [9]:
x = nd.array([1, 2, 3, 4])
y = nd.ones_like(x) * 3
print('x =', x)
print('y = ', y)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = 
[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>
y =  
[3. 3. 3. 3.]
<NDArray 4 @cpu(0)>
x + y 
[4. 5. 6. 7.]
<NDArray 4 @cpu(0)>
x - y 
[-2. -1.  0.  1.]
<NDArray 4 @cpu(0)>
x * y 
[ 3.  6.  9. 12.]
<NDArray 4 @cpu(0)>
x / y 
[0.33333334 0.6666667  1.         1.3333334 ]
<NDArray 4 @cpu(0)>


In [10]:
x.exp()


[ 2.7182817  7.389056  20.085537  54.59815  ]
<NDArray 4 @cpu(0)>

In [11]:
x = nd.arange(12).reshape((3,4))
print(x)
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(y.T)
# matrix multiplication
nd.dot(x, y.T)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[2. 1. 4.]
 [1. 2. 3.]
 [4. 3. 2.]
 [3. 4. 1.]]
<NDArray 4x3 @cpu(0)>



[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [12]:
print(nd.concat(x, y, dim=0))
print(nd.concat(x, y, dim=1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>


In [13]:
x == y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [14]:
print(x.sum())
print(nd.sum(x).asscalar())


[66.]
<NDArray 1 @cpu(0)>
66.0


Broadcast Mechanism

In [15]:
a = nd.arange(3).reshape((3, 1))
b = nd.arange(3).reshape((1, 3))
a, b

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1. 2.]]
 <NDArray 1x3 @cpu(0)>)

In [16]:
print(a + b)


[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
<NDArray 3x3 @cpu(0)>


Indexing and Slicing

In [17]:
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [18]:
x[2, 2] = 12
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 12. 11.]]
<NDArray 3x4 @cpu(0)>

In [19]:
x[0:2,1:3] = 15
x


[[ 0. 15. 15.  3.]
 [ 4. 15. 15.  7.]
 [ 8.  9. 12. 11.]]
<NDArray 3x4 @cpu(0)>

Saving Memory

In [20]:
before = id(y)
y = y + x
print(before, id(y))
id(y) == before

140638559993248 140638559990952


False

In [21]:
# The above type of assigning cause memory leakage. use below instead 
z = y.zeros_like()
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 140638559948584
id(z): 140638559948584


In [22]:
# Though the above operation looks good, it will still store x + y in buffer before assigning.
# Hence use below method
before = id(z)
nd.elemwise_sub(x, y, out=z)
id(z) == before

True

Mutual Transformation of NDArray and NumPy

In [23]:
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>


Exercises

In [24]:
print(x, y)
x < y


[[ 0. 15. 15.  3.]
 [ 4. 15. 15.  7.]
 [ 8.  9. 12. 11.]]
<NDArray 3x4 @cpu(0)> 
[[ 2. 16. 19.  6.]
 [ 5. 17. 18. 11.]
 [12. 12. 14. 12.]]
<NDArray 3x4 @cpu(0)>



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [25]:
a = nd.arange(12).reshape((2, 3, 2))
b = nd.arange(6).reshape((2, 3, 1))
a, b

(
 [[[ 0.  1.]
   [ 2.  3.]
   [ 4.  5.]]
 
  [[ 6.  7.]
   [ 8.  9.]
   [10. 11.]]]
 <NDArray 2x3x2 @cpu(0)>, 
 [[[0.]
   [1.]
   [2.]]
 
  [[3.]
   [4.]
   [5.]]]
 <NDArray 2x3x1 @cpu(0)>)

In [26]:
# In case of 3D tensors, first two dimensions should be same in order to do broadcast mechanism
nd.broadcast_add(a, b)


[[[ 0.  1.]
  [ 3.  4.]
  [ 6.  7.]]

 [[ 9. 10.]
  [12. 13.]
  [15. 16.]]]
<NDArray 2x3x2 @cpu(0)>

In [27]:
a = nd.arange(3).reshape((3,1))
b = nd.ones(shape=(1,1))
c = nd.arange(4).reshape(shape=(3,1))
a, b, c

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[1.]]
 <NDArray 1x1 @cpu(0)>, 
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>)

In [28]:
nd.broadcast_add(nd.dot(a, b.T), c, out=c)
c


[[0.]
 [2.]
 [4.]]
<NDArray 3x1 @cpu(0)>