<a href="https://colab.research.google.com/github/prasanth5reddy/D2L/blob/master/The%20Basics/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing Libraries

In [37]:
!pip install mxnet

Importing Libraries

In [0]:
import mxnet as mx
from mxnet import nd

In [39]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [40]:
x = x.reshape((3, 4))
x.reshape?
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [41]:
print(x.shape, x.size)

(3, 4) 12


In [42]:
x = nd.arange(14).reshape((3, -1))
print(x.shape, x.size)
x

(3, 4) 12



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [43]:
print(nd.zeros((2, 3, 4)), nd.ones((1, 2, 1)))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)> 
[[[1.]
  [1.]]]
<NDArray 1x2x1 @cpu(0)>


In [44]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 0.2444218  -0.03716067 -0.48774993 -0.02261727]
 [ 0.57461417  1.4661262   0.6862904   0.35496104]
 [ 1.0731696   0.12017461 -0.9711102  -0.77569664]]
<NDArray 3x4 @cpu(0)>