<a href="https://colab.research.google.com/github/prasanth5reddy/D2L/blob/master/The%20Basics/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing libraries

In [1]:
!pip install mxnet

Importing libraries

In [0]:
from mxnet import nd
import math

Scalars

In [3]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', nd.power(x,y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


In [4]:
# avoid this as this takes longer time to run
x.asscalar()

3.0

Vectors

In [5]:
x = nd.arange(4)
print('x = ', x)
x[2]

x =  
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>



[2.]
<NDArray 1 @cpu(0)>

Length, dimensionality and shape

In [6]:
x = x.reshape(shape=(2, 2))
print(len(x), x.shape, x.size)

2 (2, 2) 4


In [7]:
a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


Matrices

In [8]:
A = nd.arange(20).reshape((5, 4))
print(A)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>


In [9]:
print(A[:2,2:])
print(A.T)


[[2. 3.]
 [6. 7.]]
<NDArray 2x2 @cpu(0)>

[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>


Tensors

In [10]:
# tensors give us a generic way of discussing arrays with arbitrary number of axes
# Vectors are first-order tensors, and matrices are second-order tensors
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (2, 3, 4)
X = 
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


Basic properties of tensor arithmetic

In [11]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


Sums and means

In [12]:
print(x)
print(nd.sum(x))


[1. 1. 1.]
<NDArray 3 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


In [13]:
print(A)
print(nd.sum(A))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

[190.]
<NDArray 1 @cpu(0)>


In [14]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>

[9.5]
<NDArray 1 @cpu(0)>


Dot products

In [15]:

x = nd.arange(4)
y = nd.ones(4)
print(x, y, nd.dot(x, y))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>


In [16]:
nd.sum(x * y)


[6.]
<NDArray 1 @cpu(0)>

In [17]:
# we can also find cosine of angle between them using dot product
cosine = nd.dot(x, y) / (math.sqrt((nd.sum(x * x) * nd.sum(y * y)).asscalar()))
cosine


[0.8017837]
<NDArray 1 @cpu(0)>

Matrix-vector products

In [18]:
print(A, x)
nd.dot(A, x)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)> 
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>



[ 14.  38.  62.  86. 110.]
<NDArray 5 @cpu(0)>

Matrix-matrix multiplication

In [19]:
B = nd.ones(shape=(4, 3))
print(A, B)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)> 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 4x3 @cpu(0)>


In [20]:
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
<NDArray 5x3 @cpu(0)>

Norms

In [0]:
# L0 norm is number of non zero elements in a vector
# L1 norm is sum of the absolute values in a vector
# L2 norm is square root of sum of squares of values in a vector
# L-infinity norm is the largest absolute value in a vector

In [22]:
x = nd.array([0, 1, 2, -3])
print(x)

# L0 norm
print(nd.sum(x != 0))

# L1 norm
print(nd.sum(nd.abs(x)))

# L2 norm
print(nd.norm(x))

# L-infinity norm
print(nd.max(nd.abs(x)))


[ 0.  1.  2. -3.]
<NDArray 4 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>

[6.]
<NDArray 1 @cpu(0)>

[3.7416573]
<NDArray 1 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>
