<a href="https://colab.research.google.com/github/prasanth5reddy/D2L/blob/master/Deep%20Learning%20Computation/custom_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing Libraries

In [1]:
!pip install mxnet

Importing Libraries

In [0]:
from mxnet import gluon, nd
from mxnet.gluon import nn

Layers without Parameters

In [0]:
class CenteredLayer(nn.Block):
  def __init__(self, **kwargs):
    super(CenteredLayer, self).__init__(**kwargs)
    
  def forward(self, x):
    return x - x.mean()

In [4]:
layer = CenteredLayer()
layer(nd.array([1, 2, 3, 4, 5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [0]:
net = nn.Sequential()
net.add(nn.Dense(128), CenteredLayer())
net.initialize()

In [6]:
y = net(nd.random.uniform(shape=(4, 8)))
y.mean().asscalar()

-7.212293e-10

Layers with Parameters

In [7]:
params = gluon.ParameterDict()
params.get('param2', shape=(2, 3))
params

(
  Parameter param2 (shape=(2, 3), dtype=<class 'numpy.float32'>)
)

In [0]:
class MyDense(nn.Block):
  # units: the number of outputs in this layer; 
  # in_units: the number of inputs in this layer
  def __init__(self, units, in_units, **kwargs):
    super(MyDense, self).__init__(**kwargs)
    self.weight = self.params.get('weight', shape=(in_units, units))
    self.bias = self.params.get('bias', shape=(units,))
    
  def forward(self, x):
    linear = nd.dot(x, self.weight.data()) + self.bias.data()
    return nd.relu(linear)

In [9]:
dense = MyDense(units=3, in_units=5)
dense.params

mydense0_ (
  Parameter mydense0_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense0_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [10]:
dense.initialize()
dense(nd.random.uniform(shape=(2, 5)))


[[0.06917784 0.01627153 0.01029644]
 [0.02602214 0.0453731  0.        ]]
<NDArray 2x3 @cpu(0)>

In [11]:
net = nn.Sequential()
net.add(MyDense(8, in_units=64),
        MyDense(1, in_units=8))
net.initialize()
net(nd.random.uniform(shape=(2, 64)))


[[0.03820474]
 [0.04035058]]
<NDArray 2x1 @cpu(0)>