<a href="https://colab.research.google.com/github/prasanth5reddy/D2L/blob/master/Deep%20Learning%20Computation/GPUs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CUDA script

In [1]:
!rm -r 9c48ccafc15cf82a11192483bdef8d3f
!git clone https://gist.github.com/prasanth5reddy/9c48ccafc15cf82a11192483bdef8d3f.git
!sh 9c48ccafc15cf82a11192483bdef8d3f/install_cuda9.2_on_colab.sh

Cloning into '9c48ccafc15cf82a11192483bdef8d3f'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Sun May 12 06:46:53 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8    16W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+-----------------

Installing mxnet GPU version

In [2]:
!pip install mxnet-cu92

Importing Libraries

In [0]:
import mxnet as mx
from mxnet import nd
from mxnet.gluon import nn

Computing Devices

In [4]:
mx.cpu(), mx.gpu(), mx.gpu(1)

(cpu(0), gpu(0), gpu(1))

ND Array and GPUs

In [5]:
x = nd.array([1, 2, 3])
x


[1. 2. 3.]
<NDArray 3 @cpu(0)>

In [6]:
x.context

cpu(0)

Storage on the GPU

In [7]:
x = nd.ones((2, 3), ctx=mx.gpu())
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>

In [8]:
y = nd.random.uniform(shape=(2, 3))
y
# we don't have another GPU so consider x in GPU and y in CPU


[[0.5488135  0.5928446  0.71518934]
 [0.84426576 0.60276335 0.8579456 ]]
<NDArray 2x3 @cpu(0)>

Copying

In [9]:
# x + y does not work as there were in different context
z = y.copyto(mx.gpu())
x, z

(
 [[1. 1. 1.]
  [1. 1. 1.]]
 <NDArray 2x3 @gpu(0)>, 
 [[0.5488135  0.5928446  0.71518934]
  [0.84426576 0.60276335 0.8579456 ]]
 <NDArray 2x3 @gpu(0)>)

In [10]:
x + z


[[1.5488136 1.5928446 1.7151893]
 [1.8442657 1.6027634 1.8579457]]
<NDArray 2x3 @gpu(0)>

In [11]:
z = y.as_in_context(mx.gpu())
z


[[0.5488135  0.5928446  0.71518934]
 [0.84426576 0.60276335 0.8579456 ]]
<NDArray 2x3 @gpu(0)>

In [12]:
y.as_in_context(mx.cpu()) is y

True

In [13]:
x.copyto(mx.gpu()) is x

False

Gluon and GPUs

In [0]:
net = nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx=mx.gpu())

In [15]:
net(x)


[[0.04421056]
 [0.04421056]]
<NDArray 2x1 @gpu(0)>

In [16]:
net[0].weight.data()


[[ 0.00628365  0.04861524 -0.01068833]]
<NDArray 1x3 @gpu(0)>